### ISSUE TITLE
Possible permissions error preventing linguist-action environment variable output

### ISSUE THREAD

**Issue by HaydenMacDonald** [fabasoad/linguist-action#4]
## Describe the bug

Linguist-action has stopped outputting data as environment variables, making the data inaccessible to other actions in a workflow.

## Steps to Reproduce

1. Run `linguist-action` in a workflow using the following configuration
```yaml
      - name: Linguist Action
        uses: fabasoad/linguist-action@v1.0.2
        id: linguist
        with:
          path: './'
          percentage: true
```
2. See error `/linguist.rb:15:in 'new': repository path '/github/workspace/' is not owned by current user (Rugged::ConfigError) from /linguist.rb:15:in '<main>'`

## Expected behavior

The expectation is that `linguist-action` would output a environment variable that would be accessible to other actions in a workflow.

## Actual behavior

There is no environment variable.

## Screenshots

![image](https://user-images.githubusercontent.com/30080315/167460785-c5e58019-0201-463e-b6c7-3dac65923e48.png)

There is supposed to be a variable called `REPO_LANGS` (derived from `${{ steps.linguist.outputs.data }}` in the workflow file below) in the `with:` section of the logs.

## Technical information (please complete the following information)

- OS: ubuntu-latest
- `linguist-action` version 1.0.2
- Full workflow:
```yaml
name: multigitminder
on:
  push:
    branches: [ main, lang-bug ]
  issues:
    types: [ closed ]

jobs:
  multigitminder:
    runs-on: ubuntu-latest
    name: multigitminder
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v2.4.1"
        id: "todo"
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CLOSE_ISSUES: false
      # Linguist
      - name: Linguist Action
        uses: fabasoad/linguist-action@v1.0.2
        id: linguist
        with:
          path: './'
          percentage: true
      # multigitminder
      - name: multigitminder
        uses: HaydenMacDonald/multigitminder@v1.0.0
        id: multigitminder
        with:
          USERNAME: ${{ secrets.BEEMINDER_USERNAME }}
          AUTH_TOKEN: ${{ secrets.BEEMINDER_AUTH_TOKEN }}
          GOAL: multigitminder
          TARGET_LANGS: Python ## e.g. "['python', 'dockerfile', 'javascript']" or simply Python
          REPO_LANGS: ${{ steps.linguist.outputs.data }}
```
